name: Tory Service CI/CD 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: 1. Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 2. Set Yaml
      uses: microsoft/variable-substitution@v1
      with:
        files: ./src/main/resources/application-prod.yml 
      env:
        spring.server.address: ${{ secrets.HOST }}
        spring.datasource.hikari.jdbc-url: ${{ secrets.DB_URL }} 
        spring.datasource.hikari.username: ${{ secrets.DB_USERNAME }} 
        spring.datasource.hikari.password: ${{ secrets.DB_PASSWORD }}
#        spring.cloud.gcp.storage.credentials.location: ${{ secrets.STORAGE_CREDENTIALS }}
#        spring.cloud.gcp.storage.project-id: ${{ secrets.PROJECT_ID }}
#        spring.cloud.gcp.storage.bucket: ${{ secrets.BUCKET }}
        jwt.issuer: ${{ secrets.JWT_ISSUER }}
        jwt.secret_key: ${{ secrets.JWT_SECRET_KEY }}

    - name: 3. Install Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get -y install \
          apt-transport-https \
          ca-certificates \
          curl \
          software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get -y install docker-ce docker-ce-cli containerd.io
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: 4. Grant Execute Permission For Gradlew & Build gradle
      run: |
        chmod +x gradlew
        ./gradlew build -x test

    - name: 5. Docker hub login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 6. Docker image build
      run: |
        docker build -t ${{ secrets.DOCKER_ID }}/tory .

    - name: 7. Docker Hub push
      run: docker push ${{ secrets.DOCKER_ID }}/tory:beta
        
    - name: 8. Deploy to Instance
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.PRIVATE_KEY_PASSWORD }}
        run: |
          sudo docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker pull ${{ secrets.DOCKER_ID }}/tory
          sudo docker rm -f $(docker ps -qa) 2>/dev/null || true
          sudo docker-compose up -d
          sudo docker run -d --name tory -p 8081:8081 tory